import { FileText, Shield, Users, AlertTriangle, CheckCircle, Scale, Clock, Heart } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import ParticleSystem from "@/components/ParticleSystem";
import Footer from "@/components/Footer";
import { Link } from "wouter";

export default function TermsOfService() {
  const lastUpdated = "January 15, 2024";

  const keyTerms = [
    {
      term: "Service",
      definition: "The Preserving Connections platform, including our website, mobile applications, and all related services for creating and maintaining digital personas of deceased loved ones."
    },
    {
      term: "Account",
      definition: "Your registered user account that allows you to access and use our Service, including creating personas and managing your memories."
    },
    {
      term: "Content",
      definition: "Any information, data, text, photos, videos, audio recordings, or other materials you upload, submit, or share through our Service."
    },
    {
      term: "Persona",
      definition: "The digital representation of a deceased person created using artificial intelligence and based on memories, photos, and other content you provide."
    }
  ];

  const userResponsibilities = [
    {
      category: "Account Security",
      responsibilities: [
        "Maintain the confidentiality of your account credentials",
        "Notify us immediately of any unauthorized access",
        "Use strong passwords and enable two-factor authentication",
        "Accept responsibility for all activities under your account"
      ]
    },
    {
      category: "Content Standards",
      responsibilities: [
        "Ensure you have rights to all content you upload",
        "Respect the dignity and memory of the deceased",
        "Provide accurate and truthful information",
        "Respect family members' privacy and wishes"
      ]
    },
    {
      category: "Appropriate Use",
      responsibilities: [
        "Use the Service only for its intended memorial purposes",
        "Comply with all applicable laws and regulations",
        "Respect community guidelines and other users",
        "Report inappropriate content or behavior"
      ]
    }
  ];

  const prohibitedActivities = [
    "Creating personas without proper authorization from family",
    "Uploading false, misleading, or defamatory content",
    "Using the Service for commercial purposes without permission",
    "Attempting to hack, breach, or disrupt our systems",
    "Sharing login credentials or account access",
    "Creating multiple accounts to circumvent restrictions",
    "Using personas to deceive, manipulate, or harm others",
    "Violating any applicable laws or regulations"
  ];

  const intellectualProperty = [
    {
      category: "Your Content",
      description: "You retain ownership of content you upload while granting us necessary rights to provide the Service.",
      details: [
        "You own your photos, videos, and written memories",
        "You grant us license to use content for persona creation",
        "You can delete your content at any time",
        "Family members may have shared rights to certain content"
      ]
    },
    {
      category: "Our Technology",
      description: "We own the underlying technology, software, and artificial intelligence systems.",
      details: [
        "Our AI models and algorithms are proprietary",
        "The Preserving Connections brand and trademarks",
        "Software code and technical infrastructure",
        "Service design and user interface elements"
      ]
    },
    {
      category: "Generated Content",
      description: "Content generated by our AI based on your inputs has shared characteristics.",
      details: [
        "Generated responses reflect your loved one's personality",
        "Based on memories and content you provide",
        "You can modify or delete generated content",
        "We may use anonymized data to improve our AI"
      ]
    }
  ];

  const limitations = [
    {
      type: "Service Availability",
      description: "We strive for high availability but cannot guarantee uninterrupted service",
      examples: ["Scheduled maintenance periods", "Technical difficulties", "Force majeure events", "Third-party service disruptions"]
    },
    {
      type: "AI Accuracy",
      description: "Our AI technology creates approximations based on available data",
      examples: ["Responses may not perfectly match the person", "Limited by quality and quantity of input data", "AI may occasionally produce unexpected responses", "Continuous improvement of accuracy over time"]
    },
    {
      type: "Emotional Impact",
      description: "Use of the Service may have emotional effects that we cannot control",
      examples: ["Grief responses may vary", "Family members may react differently", "Professional counseling may be needed", "Individual healing timelines differ"]
    }
  ];

  const terminationReasons = [
    "Violation of these Terms of Service",
    "Fraudulent or illegal activities",
    "Abuse of other users or staff",
    "Failure to pay applicable fees",
    "Extended period of account inactivity",
    "Request by legal authorities",
    "Violation of community guidelines",
    "Technical or security concerns"
  ];

  return (
    <div className="min-h-screen relative overflow-hidden">
      {/* Background */}
      <div className="absolute inset-0 bg-gradient-to-br from-white via-purple-50/30 via-indigo-50/20 to-purple-100/50 animate-gradient-xy"></div>
      
      <div className="absolute inset-0 opacity-30">
        <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-r from-purple-200/20 via-transparent to-indigo-200/20 animate-pulse"></div>
        <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-b from-transparent via-purple-100/10 to-transparent animate-bounce-slow"></div>
      </div>

      <ParticleSystem />

      {/* Header */}
      <header className="bg-white/90 backdrop-blur-sm border-b border-purple-200/20 sticky top-0 z-40">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <Link href="/" className="flex items-center space-x-3">
              <div className="w-8 h-8 bg-gradient-to-r from-purple-500 to-purple-700 rounded-full flex items-center justify-center shadow-lg">
                <span className="text-white font-bold">∞</span>
              </div>
              <span className="text-gray-900 font-semibold text-lg">Preserving Connections</span>
            </Link>
            
            <Badge variant="outline" className="bg-purple-50 text-purple-700 border-purple-200">
              <Scale className="w-3 h-3 mr-1" />
              Terms of Service
            </Badge>
          </div>
        </div>
      </header>

      <div className="relative z-10 max-w-4xl mx-auto px-6 py-8">
        {/* Hero Section */}
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
            Terms of Service
          </h1>
          <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg p-6 mb-8">
            <p className="text-lg text-gray-700">
              These terms govern your use of Preserving Connections. By using our service, 
              you agree to these terms and our commitment to honoring your loved ones with dignity.
            </p>
            <p className="text-sm text-gray-600 mt-4">
              <strong>Last updated:</strong> {lastUpdated} • <strong>Effective date:</strong> {lastUpdated}
            </p>
          </div>
        </div>

        {/* Acceptance */}
        <Card className="bg-white/70 backdrop-blur-sm border-purple-100 shadow-lg mb-12">
          <CardHeader>
            <CardTitle className="text-2xl flex items-center space-x-3">
              <CheckCircle className="w-6 h-6 text-green-600" />
              <span>Acceptance of Terms</span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-gray-700 mb-4">
              By accessing or using Preserving Connections, you agree to be bound by these Terms of Service 
              and our Privacy Policy. If you do not agree to these terms, please do not use our service.
            </p>
            <p className="text-gray-700">
              These terms apply to all users of our service, including visitors, registered users, 
              and any other users of our service.
            </p>
          </CardContent>
        </Card>

        {/* Key Definitions */}
        <div className="mb-12">
          <h2 className="text-3xl font-bold text-gray-900 mb-8">Key Definitions</h2>
          
          <div className="space-y-4">
            {keyTerms.map((item, index) => (
              <Card key={index} className="bg-white/70 backdrop-blur-sm border-purple-100 shadow-lg">
                <CardContent className="p-6">
                  <h3 className="text-lg font-semibold text-purple-900 mb-2">"{item.term}"</h3>
                  <p className="text-gray-700">{item.definition}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* User Responsibilities */}
        <div className="mb-12">
          <h2 className="text-3xl font-bold text-gray-900 mb-8">Your Responsibilities</h2>
          
          <div className="space-y-6">
            {userResponsibilities.map((section, index) => (
              <Card key={index} className="bg-white/70 backdrop-blur-sm border-purple-100 shadow-lg">
                <CardHeader>
                  <CardTitle className="text-xl">{section.category}</CardTitle>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2">
                    {section.responsibilities.map((responsibility, respIndex) => (
                      <li key={respIndex} className="flex items-start space-x-2">
                        <CheckCircle className="w-4 h-4 text-green-500 mt-0.5" />
                        <span className="text-gray-700">{responsibility}</span>
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Prohibited Activities */}
        <Card className="bg-gradient-to-r from-red-50 to-orange-50 border-red-200 mb-12">
          <CardHeader>
            <CardTitle className="text-2xl flex items-center space-x-3 text-red-900">
              <AlertTriangle className="w-6 h-6 text-red-600" />
              <span>Prohibited Activities</span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-red-800 mb-6">
              The following activities are strictly prohibited and may result in account termination:
            </p>
            
            <ul className="space-y-2">
              {prohibitedActivities.map((activity, index) => (
                <li key={index} className="flex items-start space-x-2">
                  <AlertTriangle className="w-4 h-4 text-red-500 mt-0.5" />
                  <span className="text-red-800">{activity}</span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>

        {/* Intellectual Property */}
        <div className="mb-12">
          <h2 className="text-3xl font-bold text-gray-900 mb-8">Intellectual Property Rights</h2>
          
          <div className="space-y-6">
            {intellectualProperty.map((ip, index) => (
              <Card key={index} className="bg-white/70 backdrop-blur-sm border-purple-100 shadow-lg">
                <CardHeader>
                  <CardTitle className="text-xl">{ip.category}</CardTitle>
                  <p className="text-gray-600">{ip.description}</p>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2">
                    {ip.details.map((detail, detailIndex) => (
                      <li key={detailIndex} className="flex items-start space-x-2">
                        <CheckCircle className="w-4 h-4 text-blue-500 mt-0.5" />
                        <span className="text-gray-700">{detail}</span>
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Limitations and Disclaimers */}
        <div className="mb-12">
          <h2 className="text-3xl font-bold text-gray-900 mb-8">Service Limitations</h2>
          
          <div className="space-y-6">
            {limitations.map((limitation, index) => (
              <Card key={index} className="bg-white/70 backdrop-blur-sm border-purple-100 shadow-lg">
                <CardHeader>
                  <CardTitle className="text-xl">{limitation.type}</CardTitle>
                  <p className="text-gray-600">{limitation.description}</p>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2">
                    {limitation.examples.map((example, exampleIndex) => (
                      <li key={exampleIndex} className="flex items-start space-x-2">
                        <Clock className="w-4 h-4 text-amber-500 mt-0.5" />
                        <span className="text-gray-700">{example}</span>
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Termination */}
        <Card className="bg-white/70 backdrop-blur-sm border-purple-100 shadow-lg mb-12">
          <CardHeader>
            <CardTitle className="text-2xl">Account Termination</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-gray-700 mb-6">
              We reserve the right to suspend or terminate your account and access to the Service 
              at our discretion, including for the following reasons:
            </p>
            
            <ul className="space-y-2 mb-6">
              {terminationReasons.map((reason, index) => (
                <li key={index} className="flex items-start space-x-2">
                  <AlertTriangle className="w-4 h-4 text-orange-500 mt-0.5" />
                  <span className="text-gray-700">{reason}</span>
                </li>
              ))}
            </ul>
            
            <div className="bg-blue-50 rounded-lg p-4 border border-blue-200">
              <h4 className="font-semibold text-blue-900 mb-2">Upon Termination:</h4>
              <ul className="text-sm text-blue-800 space-y-1">
                <li>• Your access to the Service will cease immediately</li>
                <li>• You may download your data within 30 days of termination</li>
                <li>• We will delete your account data according to our retention policy</li>
                <li>• Some provisions of these terms will survive termination</li>
              </ul>
            </div>
          </CardContent>
        </Card>

        {/* Liability and Indemnification */}
        <Card className="bg-gradient-to-r from-amber-50 to-orange-50 border-amber-200 mb-12">
          <CardHeader>
            <CardTitle className="text-2xl text-amber-900">Limitation of Liability</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-amber-800 mb-4">
              To the maximum extent permitted by law, Preserving Connections shall not be liable for any indirect, 
              incidental, special, consequential, or punitive damages arising from your use of the Service.
            </p>
            
            <div className="space-y-3 text-amber-800">
              <p><strong>Service Provided "As Is":</strong> We provide the Service without warranties of any kind.</p>
              <p><strong>Your Use:</strong> You use the Service at your own risk and discretion.</p>
              <p><strong>Emotional Impact:</strong> We are not responsible for emotional effects of using our Service.</p>
              <p><strong>Third Parties:</strong> We are not liable for actions of third-party service providers.</p>
            </div>
          </CardContent>
        </Card>

        {/* Governing Law */}
        <Card className="bg-white/70 backdrop-blur-sm border-purple-100 shadow-lg mb-12">
          <CardHeader>
            <CardTitle className="text-2xl flex items-center space-x-3">
              <Scale className="w-6 h-6 text-purple-600" />
              <span>Governing Law and Disputes</span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div>
                <h4 className="font-semibold text-gray-900 mb-2">Governing Law</h4>
                <p className="text-gray-700">
                  These Terms are governed by the laws of the State of Delaware, without regard to conflict of law principles.
                </p>
              </div>
              
              <div>
                <h4 className="font-semibold text-gray-900 mb-2">Dispute Resolution</h4>
                <p className="text-gray-700 mb-2">
                  We encourage resolving disputes through direct communication first. For formal disputes:
                </p>
                <ul className="space-y-1 text-gray-700">
                  <li>• Initial resolution through mediation</li>
                  <li>• Binding arbitration if mediation fails</li>
                  <li>• Jurisdiction in Delaware courts for any legal proceedings</li>
                  <li>• Class action waiver applies</li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Changes to Terms */}
        <Card className="bg-gradient-to-r from-purple-50 to-indigo-50 border-purple-200 mb-12">
          <CardContent className="p-8 text-center">
            <Heart className="w-12 h-12 text-purple-600 mx-auto mb-4" />
            <h3 className="text-2xl font-bold text-gray-900 mb-4">Changes to These Terms</h3>
            <p className="text-gray-700 mb-6">
              We may update these Terms of Service from time to time. When we do:
            </p>
            
            <div className="grid md:grid-cols-2 gap-6 text-left">
              <div>
                <h4 className="font-semibold text-purple-900 mb-2">We Will:</h4>
                <ul className="space-y-1 text-purple-800">
                  <li>• Update the "Last updated" date</li>
                  <li>• Notify you of significant changes</li>
                  <li>• Give you time to review changes</li>
                  <li>• Maintain previous versions for reference</li>
                </ul>
              </div>
              
              <div>
                <h4 className="font-semibold text-purple-900 mb-2">Your Options:</h4>
                <ul className="space-y-1 text-purple-800">
                  <li>• Review changes carefully</li>
                  <li>• Contact us with questions</li>
                  <li>• Accept changes by continuing to use the Service</li>
                  <li>• Discontinue use if you disagree</li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Contact Information */}
        <Card className="bg-gradient-to-r from-green-50 to-emerald-50 border-green-200">
          <CardContent className="p-8 text-center">
            <h3 className="text-2xl font-bold text-gray-900 mb-4">Questions About These Terms?</h3>
            <p className="text-gray-700 mb-6">
              If you have questions about these Terms of Service, please contact us:
            </p>
            
            <div className="grid md:grid-cols-3 gap-4 text-sm">
              <div>
                <h4 className="font-medium text-gray-900 mb-1">Email</h4>
                <p className="text-green-700">legal@preservingconnections.app</p>
              </div>
              <div>
                <h4 className="font-medium text-gray-900 mb-1">Mail</h4>
                <p className="text-gray-600">
                  Preserving Connections<br />
                  Legal Department<br />
                  123 Main St, Suite 100<br />
                  Anytown, ST 12345
                </p>
              </div>
              <div>
                <h4 className="font-medium text-gray-900 mb-1">Support</h4>
                <p className="text-green-700">support@preservingconnections.app</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <Footer />
    </div>
  );
}